# -*- coding: utf-8 -*-
"""bubble sort.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_cyHeAakL9JfRvDKF24ywKutehbbBtZy
"""

# Bubble Sort
def bubble_sort(arr):
    for i in range(len(arr)):
        for j in range(0, len(arr) - i - 1):
            if arr[j] > arr[j + 1]:
                arr[j], arr[j + 1] = arr[j + 1], arr[j]
    return arr

# Sample array
arr = [64, 34, 25, 12, 22, 11, 90]

# Sort the array using bubble sort
sorted_arr = bubble_sort(arr)

# Print the sorted array
print("Sorted array:", sorted_arr)